// Starter deck. [dutch, english, type, category]
const STARTER = [
["hallo","hello","word","Basics"],["dag","bye / hello","word","Basics"],["alstublieft","please (formal)","word","Basics"],
["alsjeblieft","please / here you go","word","Basics"],["dank je wel","thank you","phrase","Basics"],["graag gedaan","you're welcome","phrase","Basics"],
["ja","yes","word","Basics"],["nee","no","word","Basics"],["misschien","maybe","word","Basics"],["sorry","sorry","word","Basics"],
["goedemorgen","good morning","word","Greetings"],["goedemiddag","good afternoon","word","Greetings"],["goedenavond","good evening","word","Greetings"],
["goedenacht","good night","word","Greetings"],["tot ziens","see you later","phrase","Greetings"],["tot morgen","see you tomorrow","phrase","Greetings"],
["Hoe gaat het met je?","How are you?","phrase","Greetings"],["Het gaat goed, dank je.","I'm doing well, thanks.","phrase","Greetings"],
["Hoe heet je?","What's your name?","phrase","Greetings"],["Ik heet …","My name is …","phrase","Greetings"],["Aangenaam","Nice to meet you","word","Greetings"],
["Ik begrijp het niet.","I don't understand.","phrase","Survival"],["Kun je dat herhalen?","Can you repeat that?","phrase","Survival"],
["Spreek je Engels?","Do you speak English?","phrase","Survival"],["Ik spreek een beetje Nederlands.","I speak a little Dutch.","phrase","Survival"],
["Langzamer, alsjeblieft.","Slower, please.","phrase","Survival"],["Wat betekent dat?","What does that mean?","phrase","Survival"],
["Waar is het toilet?","Where is the toilet?","phrase","Survival"],["Help!","Help!","word","Survival"],
["ik","I","word","Pronouns"],["jij / je","you (informal)","word","Pronouns"],["u","you (formal)","word","Pronouns"],["hij","he","word","Pronouns"],
["zij / ze","she / they","word","Pronouns"],["wij / we","we","word","Pronouns"],["jullie","you (plural)","word","Pronouns"],
["zijn","to be","word","Verbs"],["hebben","to have","word","Verbs"],["gaan","to go","word","Verbs"],["komen","to come","word","Verbs"],
["doen","to do","word","Verbs"],["maken","to make","word","Verbs"],["willen","to want","word","Verbs"],["kunnen","can / to be able","word","Verbs"],
["moeten","must / to have to","word","Verbs"],["eten","to eat","word","Verbs"],["drinken","to drink","word","Verbs"],["slapen","to sleep","word","Verbs"],
["werken","to work","word","Verbs"],["spreken","to speak","word","Verbs"],["kopen","to buy","word","Verbs"],["zien","to see","word","Verbs"],["weten","to know (a fact)","word","Verbs"],
["het water","the water","word","Food"],["het brood","the bread","word","Food"],["de kaas","the cheese","word","Food"],["de melk","the milk","word","Food"],
["de koffie","the coffee","word","Food"],["de appel","the apple","word","Food"],["het ontbijt","breakfast","word","Food"],["de lunch","lunch","word","Food"],["het avondeten","dinner","word","Food"],
["Ik heb honger.","I'm hungry.","phrase","Food"],["Ik heb dorst.","I'm thirsty.","phrase","Food"],["Eet smakelijk!","Enjoy your meal!","phrase","Food"],
["Mag ik de rekening?","Can I have the bill?","phrase","Food"],["Ik wil graag een koffie.","I'd like a coffee.","phrase","Food"],["Het is lekker.","It's tasty.","phrase","Food"],
["een","one","word","Numbers"],["twee","two","word","Numbers"],["drie","three","word","Numbers"],["vier","four","word","Numbers"],["vijf","five","word","Numbers"],
["zes","six","word","Numbers"],["zeven","seven","word","Numbers"],["acht","eight","word","Numbers"],["negen","nine","word","Numbers"],["tien","ten","word","Numbers"],
["maandag","Monday","word","Time"],["dinsdag","Tuesday","word","Time"],["woensdag","Wednesday","word","Time"],["donderdag","Thursday","word","Time"],
["vrijdag","Friday","word","Time"],["zaterdag","Saturday","word","Time"],["zondag","Sunday","word","Time"],["vandaag","today","word","Time"],
["morgen","tomorrow","word","Time"],["gisteren","yesterday","word","Time"],["Hoe laat is het?","What time is it?","phrase","Time"],
["het huis","the house","word","Places"],["de stad","the city","word","Places"],["de winkel","the shop","word","Places"],["het station","the station","word","Places"],
["de school","the school","word","Places"],["Waar is …?","Where is …?","phrase","Places"],["Ik woon in …","I live in …","phrase","Places"],
["links","left","word","Places"],["rechts","right","word","Places"],["rechtdoor","straight ahead","word","Places"],
["groot","big","word","Adjectives"],["klein","small","word","Adjectives"],["goed","good","word","Adjectives"],["slecht","bad","word","Adjectives"],
["mooi","beautiful","word","Adjectives"],["moe","tired","word","Adjectives"],["blij","happy","word","Adjectives"],["koud","cold","word","Adjectives"],["warm","warm / hot","word","Adjectives"]
];
