// Situation-based deck (Belgian Dutch / Flemish usage). Each card: [dutch, english, note?]
// Rules: one complete phrase or word per card (no "a / b" lists, no "…" blanks) so every
// card works for writing, dictation and speaking levels.
// A note starting with "👂" marks something you'll HEAR (so you recognise it), not something you say.
const CATEGORIES = [
{ name: "At the kassa (work)", emoji: "🧾", cards: [
  ["Goedendag, wat mag het zijn?", "Hello, what can I get you?", "Use 'u' with customers, not 'je'"],
  ["Wie mag ik helpen?", "Who can I help? (who's next?)", "Say this to call the next customer"],
  ["Is het om hier op te eten of om mee te nemen?", "Is it to eat here or to take away?"],
  ["Om mee te nemen.", "To take away.", "👂 Customer's answer"],
  ["Om hier op te eten.", "To eat here.", "👂 Customer's answer"],
  ["Een kleine friet met mayonaise, alstublieft.", "A small fries with mayo, please.", "👂 Classic Belgian order"],
  ["Zonder ui, alstublieft.", "Without onion, please.", "👂 Customer request"],
  ["Met extra kaas, alstublieft.", "With extra cheese, please.", "👂 Customer request"],
  ["Groot of klein?", "Large or small?"],
  ["Welke saus wilt u?", "Which sauce would you like?"],
  ["Wilt u er iets bij drinken?", "Would you like a drink with that?"],
  ["Nog iets anders?", "Anything else?"],
  ["Dat is alles.", "That's everything.", "👂 Customer's answer"],
  ["Mag ik uw naam?", "May I have your name?", "For writing on the order"],
  ["Dat is dan twaalf euro vijftig.", "That'll be twelve euros fifty."],
  ["Dat is dan acht euro twintig.", "That'll be eight euros twenty."],
  ["Dat is dan vijftien euro.", "That'll be fifteen euros."],
  ["Met de kaart of cash?", "Card or cash?"],
  ["U mag contactloos betalen.", "You can pay contactless."],
  ["U mag uw kaart insteken.", "You can insert your card."],
  ["Uw code, alstublieft.", "Your PIN, please."],
  ["Het is gelukt.", "It went through."],
  ["Het is niet gelukt.", "It didn't go through."],
  ["Kunt u het opnieuw proberen?", "Could you try again?"],
  ["Heeft u het gepast?", "Do you have the exact change?"],
  ["Hier is uw wisselgeld.", "Here's your change."],
  ["Wilt u een ticketje?", "Would you like a receipt?", "Flemish: 'ticketje' = receipt"],
  ["Even geduld, alstublieft.", "Please be patient a moment."],
  ["Het duurt ongeveer tien minuten.", "It'll take about ten minutes."],
  ["Uw bestelling is klaar!", "Your order is ready!"],
  ["Nummer zeventien, alstublieft!", "Number seventeen, please!", "Calling out an order number"],
  ["Zit er gluten in?", "Is there gluten in it?", "👂 Customer question"],
  ["Is dit vegetarisch?", "Is this vegetarian?", "👂 Customer question"],
  ["Is dit pikant?", "Is this spicy?", "👂 Customer question"],
  ["Ik vraag het even na in de keuken.", "I'll quickly check with the kitchen."],
  ["Sorry, dat is op.", "Sorry, that's sold out."],
  ["Sorry, dat hebben we niet.", "Sorry, we don't have that."],
  ["Ik roep even mijn collega.", "I'll call my colleague."],
  ["Kunt u dat herhalen, alstublieft?", "Could you repeat that, please?", "Formal version — use with customers"],
  ["Smakelijk!", "Enjoy! (short for 'eet smakelijk')"],
  ["Bedankt en nog een fijne dag!", "Thank you and have a nice day!"],
]},
{ name: "In the kitchen (work)", emoji: "👨‍🍳", cards: [
  ["Ja, chef!", "Yes, chef!"],
  ["Goeiemorgen allemaal!", "Good morning, everyone!", "'Goeiemorgen' is how 'goedemorgen' is said"],
  ["Wat moet ik doen?", "What should I do?"],
  ["Wat moet ik eerst doen?", "What should I do first?"],
  ["Kun je dit snijden?", "Can you cut this?", "👂 From the chef or a colleague"],
  ["Snij de uien in blokjes.", "Dice the onions.", "👂 'blokjes' = cubes"],
  ["Snij het in reepjes.", "Cut it into strips.", "👂"],
  ["Snij het in plakjes.", "Cut it into slices.", "👂"],
  ["Schil de aardappelen.", "Peel the potatoes.", "👂"],
  ["Zet dit in de frigo.", "Put this in the fridge.", "👂 Flemish: 'frigo' = fridge"],
  ["Haal het uit de diepvries.", "Take it out of the freezer.", "👂"],
  ["Zet de oven op tweehonderd graden.", "Set the oven to two hundred degrees.", "👂"],
  ["Waar staat de grote pan?", "Where is the big pan?", "'staan' = to be (standing) somewhere"],
  ["Achter je!", "Behind you!", "Shout this when passing behind someone"],
  ["Heet! Pas op!", "Hot! Watch out!"],
  ["Mes!", "Knife!", "Warn others when carrying a knife"],
  ["Bon!", "Order in!", "'bon' = the order ticket"],
  ["Tafel vijf is klaar.", "Table five is ready."],
  ["Hoeveel porties?", "How many portions?"],
  ["Hoeveel moet ik er maken?", "How many should I make?"],
  ["Ik ben bijna klaar.", "I'm almost done."],
  ["Ik ben klaar, wat nu?", "I'm done, what next?"],
  ["We hebben geen tomaten meer.", "We're out of tomatoes."],
  ["Is dit gaar?", "Is this cooked through?"],
  ["Het is nog niet gaar.", "It's not cooked yet."],
  ["Proef eens.", "Have a taste.", "👂"],
  ["Het is te zout.", "It's too salty."],
  ["Er mist iets.", "Something is missing."],
  ["Kun je de afwas doen?", "Can you do the dishes?", "👂"],
  ["Kun je de vloer dweilen?", "Can you mop the floor?", "👂"],
  ["Maak je werkplek proper.", "Clean your workstation.", "👂 Flemish: 'proper' = clean"],
  ["Was je handen.", "Wash your hands.", "👂"],
  ["Kun je even helpen?", "Can you help for a moment?"],
  ["Ik heb me gesneden.", "I've cut myself."],
  ["Ik heb me verbrand.", "I've burnt myself."],
  ["Waar is de verbandkist?", "Where is the first-aid kit?"],
  ["het mes", "the knife"],
  ["de snijplank", "the cutting board"],
  ["de koekenpan", "the frying pan"],
  ["de kookpot", "the cooking pot", "Flemish: 'pot' — in the Netherlands they say 'pan'"],
  ["de oven", "the oven"],
  ["de friteuse", "the deep fryer"],
  ["het bord", "the plate"],
  ["het bestek", "the cutlery"],
  ["het schort", "the apron"],
  ["de handschoenen", "the gloves"],
  ["snijden", "to cut"],
  ["bakken", "to fry / to bake"],
  ["koken", "to cook / to boil"],
  ["frituren", "to deep-fry"],
  ["de ui", "the onion"],
  ["de tomaat", "the tomato"],
  ["de aardappel", "the potato"],
  ["de saus", "the sauce"],
  ["de kruiden", "the herbs and spices"],
]},
{ name: "Shifts & boss (work)", emoji: "📅", cards: [
  ["Wanneer moet ik werken?", "When do I have to work?"],
  ["Wanneer is mijn volgende shift?", "When is my next shift?"],
  ["Hoe laat begin ik morgen?", "What time do I start tomorrow?"],
  ["Hoe laat stop ik vandaag?", "What time do I finish today?"],
  ["Wie sluit vandaag af?", "Who's closing today?"],
  ["Is het uurrooster al klaar?", "Is the schedule ready yet?", "Flemish: 'uurrooster' = (work) schedule"],
  ["Kan ik zaterdag vrij krijgen?", "Can I get Saturday off?"],
  ["Kan ik met iemand wisselen?", "Can I swap (shifts) with someone?"],
  ["Ik kan vandaag niet komen, ik ben ziek.", "I can't come in today, I'm sick."],
  ["Ik ben tien minuten te laat, sorry.", "I'm ten minutes late, sorry."],
  ["Mag ik even pauze nemen?", "May I take a short break?"],
  ["Ik neem even pauze.", "I'm taking a short break."],
  ["Ik heb een vraag over mijn loon.", "I have a question about my pay."],
  ["Waar is mijn loonbrief?", "Where is my payslip?", "Flemish: 'loonbrief' = payslip"],
  ["Hoeveel uren heb ik deze week?", "How many hours do I have this week?"],
  ["Ik kan extra uren doen.", "I can do extra hours."],
  ["Wat moet ik nog doen voor ik ga?", "What do I still need to do before I leave?"],
  ["Mag ik naar huis?", "May I go home?"],
  ["Goed gewerkt vandaag!", "Good work today!", "👂 From your boss — say 'Dank je!'"],
  ["Bedankt voor je hulp.", "Thanks for your help."],
  ["Tot morgen, allemaal!", "See you tomorrow, everyone!"],
  ["de baas", "the boss"],
  ["de collega", "the colleague"],
]},
{ name: "Meeting someone", emoji: "👋", cards: [
  ["Hallo!", "Hello!"],
  ["Hoi!", "Hi!"],
  ["Hoe heet je?", "What's your name?"],
  ["Ik heet Alex.", "My name is Alex.", "Practise it with your own name"],
  ["Aangenaam!", "Nice to meet you!"],
  ["Hoe gaat het met je?", "How are you?", "Short: 'Hoe gaat het?' — Flemish people also say 'Ça va?'"],
  ["Goed, en met jou?", "Good, and you?"],
  ["Het gaat goed, dank je.", "I'm doing well, thanks."],
  ["Niet slecht.", "Not bad."],
  ["Waar kom je vandaan?", "Where are you from?"],
  ["Ik kom uit Spanje.", "I'm from Spain.", "Swap in your own country"],
  ["Waar woon je?", "Where do you live?"],
  ["Ik woon in Antwerpen.", "I live in Antwerp."],
  ["Hoe lang woon je al hier?", "How long have you lived here?"],
  ["Ik woon hier al een jaar.", "I've lived here for a year."],
  ["Wat doe je?", "What do you do (for a living)?"],
  ["Ik ben student.", "I'm a student."],
  ["Ik studeer aan de KdG.", "I study at KdG."],
  ["Ik werk in een restaurant.", "I work in a restaurant."],
  ["Hoe oud ben je?", "How old are you?"],
  ["Ik ben twintig jaar.", "I'm twenty.", "Swap in your own age"],
  ["Spreek je Engels?", "Do you speak English?"],
  ["Ik leer Nederlands.", "I'm learning Dutch."],
  ["Ik spreek een beetje Nederlands.", "I speak a little Dutch."],
  ["Je Nederlands is goed!", "Your Dutch is good!", "👂 You'll hear this — say 'Dank je!'"],
  ["Dank je, ik doe mijn best.", "Thanks, I'm doing my best."],
  ["Leuk je te ontmoeten!", "Nice meeting you! (when leaving)"],
  ["Tot ziens!", "Goodbye!"],
  ["Tot later!", "See you later!"],
  ["Daag!", "Bye!", "Very common Flemish goodbye"],
]},
{ name: "Small talk", emoji: "💬", cards: [
  ["Wat een mooi weer, hè!", "What nice weather, huh!"],
  ["Het regent weer.", "It's raining again."],
  ["Het is koud vandaag.", "It's cold today."],
  ["Het is warm vandaag.", "It's warm today."],
  ["Hoe was je dag?", "How was your day?"],
  ["Wat ga je dit weekend doen?", "What are you doing this weekend?"],
  ["Heb je een leuk weekend gehad?", "Did you have a nice weekend?"],
  ["Ik ga naar de stad.", "I'm going into town."],
  ["Ik moet werken.", "I have to work."],
  ["Wat zijn je hobby's?", "What are your hobbies?"],
  ["Ik hou van sporten.", "I like doing sports."],
  ["Ik hou van muziek.", "I love music."],
  ["Ik kijk graag naar films.", "I like watching films."],
  ["Ik kook graag.", "I like cooking."],
  ["Welke muziek vind je leuk?", "What music do you like?"],
  ["Heb je broers of zussen?", "Do you have brothers or sisters?"],
  ["Ik heb een broer en een zus.", "I have a brother and a sister."],
  ["Dat is leuk!", "That's nice / fun!"],
  ["Echt?", "Really?"],
  ["Zeker!", "Definitely!"],
  ["Geen idee.", "No idea."],
  ["Dat klopt.", "That's right."],
  ["Ik ook!", "Me too!"],
  ["Ik ook niet.", "Me neither."],
]},
{ name: "Understanding", emoji: "🤔", cards: [
  ["Sorry, ik begrijp het niet.", "Sorry, I don't understand."],
  ["Kun je dat herhalen?", "Can you repeat that?"],
  ["Kun je langzamer praten?", "Can you speak more slowly?"],
  ["Wat betekent dat?", "What does that mean?"],
  ["Wat betekent dit woord?", "What does this word mean?"],
  ["Hoe zeg je dat in het Nederlands?", "How do you say that in Dutch?"],
  ["Hoe spreek je dit uit?", "How do you pronounce this?"],
  ["Hoe spel je dat?", "How do you spell that?"],
  ["Kun je dat opschrijven?", "Can you write that down?"],
  ["Kun je het in het Engels zeggen?", "Can you say it in English?"],
  ["Bedoel je dit?", "Do you mean this?"],
  ["Is dat juist?", "Is that correct?"],
  ["Ik weet niet hoe je dat zegt.", "I don't know how to say that."],
  ["Ik ben nog aan het leren.", "I'm still learning."],
  ["Verbeter me gerust.", "Feel free to correct me."],
  ["Een momentje, alsjeblieft.", "Just a moment, please."],
  ["Ah, nu begrijp ik het!", "Ah, now I understand!"],
  ["Wablieft?", "Pardon? / Come again?", "Very Flemish — you'll hear it a lot"],
]},
{ name: "Opinions & feelings", emoji: "💭", cards: [
  ["Ik vind het leuk.", "I like it."],
  ["Ik vind het niet leuk.", "I don't like it."],
  ["Ik vind het lekker.", "I think it's tasty."],
  ["Dat vind ik ook.", "I think so too."],
  ["Ik denk het wel.", "I think so."],
  ["Ik denk het niet.", "I don't think so."],
  ["Ik ben het met je eens.", "I agree with you."],
  ["Ik ben moe.", "I'm tired."],
  ["Ik ben blij.", "I'm happy."],
  ["Ik ben een beetje zenuwachtig.", "I'm a bit nervous."],
  ["Ik heb het druk.", "I'm busy."],
  ["Ik heb honger.", "I'm hungry.", "Literally 'I have hunger'"],
  ["Ik heb dorst.", "I'm thirsty."],
  ["Ik heb het koud.", "I'm cold.", "Not 'Ik ben koud'!"],
  ["Ik heb het warm.", "I'm hot."],
  ["Geen zorgen.", "No worries."],
  ["Dat maakt niet uit.", "It doesn't matter."],
  ["Wat jammer!", "What a pity!"],
  ["Gezellig!", "Cosy! / Nice and sociable!", "A very Dutch word for a warm, fun atmosphere"],
  ["Proficiat!", "Congratulations!", "Flemish — in the Netherlands: 'Gefeliciteerd!'"],
  ["Veel succes!", "Good luck!"],
  ["Beterschap!", "Get well soon!"],
]},
{ name: "Shop", emoji: "🛍️", cards: [
  ["Goedendag!", "Good day!", "Standard Flemish greeting when entering a shop"],
  ["Kan ik u helpen?", "Can I help you?", "👂 Shop staff will ask this"],
  ["Ik kijk gewoon even rond.", "I'm just looking around."],
  ["Ik zoek een jas.", "I'm looking for a coat."],
  ["Ik zoek een cadeau.", "I'm looking for a present."],
  ["Welke maat heeft u?", "What size are you?", "👂"],
  ["Heeft u dit in een andere maat?", "Do you have this in another size?"],
  ["Heeft u dit in een andere kleur?", "Do you have this in another colour?"],
  ["Mag ik dit passen?", "Can I try this on?"],
  ["Waar zijn de paskamers?", "Where are the fitting rooms?"],
  ["Het is te groot.", "It's too big."],
  ["Het is te klein.", "It's too small."],
  ["Het past goed.", "It fits well."],
  ["Hoeveel kost dit?", "How much does this cost?"],
  ["Dat is te duur.", "That's too expensive."],
  ["Is er korting?", "Is there a discount?"],
  ["Ik neem het.", "I'll take it."],
  ["Mag ik met de kaart betalen?", "Can I pay by card?"],
  ["Contactloos, alstublieft.", "Contactless, please."],
  ["Wilt u een zakje?", "Would you like a bag?", "👂 Cashier question"],
  ["Nee, dank u, ik heb een tas.", "No thanks, I have a bag."],
  ["Wilt u het ticketje?", "Do you want the receipt?", "👂 'ticketje' = receipt in Flanders"],
  ["Mag ik dit ruilen?", "Can I exchange this?"],
  ["Mag ik dit terugbrengen?", "Can I return this?"],
  ["Nog een prettige dag!", "Have a nice day!"],
]},
{ name: "Supermarket", emoji: "🛒", cards: [
  ["Waar vind ik de melk?", "Where can I find the milk?"],
  ["Waar liggen de eieren?", "Where are the eggs?", "'liggen' = to lie — used for things lying on shelves"],
  ["Heeft u nog brood?", "Do you have any bread left?"],
  ["Is dit in promotie?", "Is this on offer?", "Flemish: 'promotie' = special offer"],
  ["Is deze kassa open?", "Is this checkout open?"],
  ["Heeft u een klantenkaart?", "Do you have a loyalty card?", "👂 Cashier question"],
  ["Nee, die heb ik niet.", "No, I don't have one."],
  ["Mag ik een zakje?", "Can I have a bag?"],
  ["het brood", "the bread"],
  ["de kaas", "the cheese"],
  ["de melk", "the milk"],
  ["de boter", "the butter"],
  ["de eieren", "the eggs"],
  ["de groenten", "the vegetables"],
  ["het fruit", "the fruit"],
  ["het vlees", "the meat"],
  ["de kip", "the chicken"],
  ["de vis", "the fish"],
  ["de rijst", "the rice"],
  ["het water", "the water"],
  ["de kassa", "the checkout"],
  ["een winkelkar", "a shopping trolley", "Flemish — in the Netherlands: 'winkelwagen'"],
  ["een mandje", "a basket"],
]},
{ name: "Bakery", emoji: "🥖", cards: [
  ["Wie is er aan de beurt?", "Who's next?", "👂 Staff calling the next customer"],
  ["Ik ben aan de beurt.", "It's my turn."],
  ["Een wit brood, alstublieft.", "A white loaf, please."],
  ["Een bruin brood, alstublieft.", "A brown loaf, please."],
  ["Gesneden, alstublieft.", "Sliced, please."],
  ["Niet gesneden, alstublieft.", "Unsliced, please."],
  ["Twee pistolets, alstublieft.", "Two bread rolls, please.", "Flemish: 'pistolet' = round crusty roll"],
  ["Een croissant, alstublieft.", "A croissant, please."],
  ["Vier koffiekoeken, alstublieft.", "Four pastries, please.", "Flemish: 'koffiekoek' = sweet pastry"],
  ["Mag het iets meer zijn?", "Anything more? (lit. 'may it be a bit more?')", "👂 Staff asking if you want anything else"],
  ["Nee, dat is alles.", "No, that's everything."],
  ["Dat is alles, dank u.", "That's all, thank you."],
  ["Tot hoe laat bent u open?", "Until what time are you open?"],
  ["Hoeveel kost een brood?", "How much is a loaf?"],
  ["Heeft u nog pistolets?", "Do you have any rolls left?"],
]},
{ name: "Café & restaurant", emoji: "🍽️", cards: [
  ["Een tafel voor twee, alstublieft.", "A table for two, please."],
  ["Heeft u een reservatie?", "Do you have a reservation?", "👂 Flemish: 'reservatie'"],
  ["Ik heb gereserveerd op naam van Peeters.", "I have a reservation under the name Peeters.", "Swap in your own name"],
  ["Mag ik de kaart, alstublieft?", "Can I have the menu, please?"],
  ["Wat wilt u drinken?", "What would you like to drink?", "👂 Waiter question"],
  ["Ik wil graag een cola.", "I'd like a cola."],
  ["Een koffie, alstublieft.", "A coffee, please."],
  ["Een pintje, alstublieft.", "A beer (small draught), please.", "Flemish: 'pintje' = glass of lager"],
  ["Nog een pintje, alstublieft.", "Another beer, please."],
  ["Een kraantjeswater, alstublieft.", "A tap water, please."],
  ["Plat of bruis?", "Still or sparkling?", "👂 About water"],
  ["Wat raadt u aan?", "What do you recommend?"],
  ["Wat is de dagschotel?", "What's the dish of the day?"],
  ["Ik neem de soep.", "I'll have the soup."],
  ["Voor mij de spaghetti.", "The spaghetti for me."],
  ["Ik ben vegetariër.", "I'm vegetarian."],
  ["Ik ben allergisch voor noten.", "I'm allergic to nuts."],
  ["Zit er vlees in?", "Is there meat in it?"],
  ["Alles in orde?", "Is everything OK?", "👂 Waiter checking on you"],
  ["Het is heel lekker!", "It's very tasty!"],
  ["Eet smakelijk!", "Enjoy your meal!"],
  ["Mag ik de rekening, alstublieft?", "Can I have the bill, please?"],
  ["Samen of apart?", "Together or separately?", "👂 About paying"],
  ["Apart, alstublieft.", "Separately, please."],
  ["Kan ik hier met de kaart betalen?", "Can I pay by card here?"],
  ["Laat maar zitten.", "Keep the change."],
]},
{ name: "Going out & friends", emoji: "🎉", cards: [
  ["Heb je zin om iets te drinken?", "Do you feel like getting a drink?"],
  ["Heb je vanavond tijd?", "Are you free tonight?"],
  ["Zullen we iets afspreken?", "Shall we meet up?"],
  ["Waar spreken we af?", "Where shall we meet?"],
  ["Om hoe laat?", "At what time?"],
  ["Goed idee!", "Good idea!"],
  ["Zin in!", "Looking forward to it!"],
  ["Spijtig, ik kan niet.", "Sorry, I can't make it.", "Flemish: 'spijtig' = a pity"],
  ["Ik kom wat later.", "I'll be a bit late."],
  ["Ik ben er bijna.", "I'm almost there."],
  ["Wat drink je?", "What are you drinking?"],
  ["Ik trakteer!", "My treat!"],
  ["Schol!", "Cheers!", "In Flanders you'll also hear 'Santé!'"],
  ["Mag ik je nummer?", "Can I have your number?"],
  ["Stuur me een berichtje.", "Send me a message."],
  ["Het was heel gezellig!", "It was really nice!"],
  ["Ik moet naar huis.", "I have to go home."],
  ["Tot de volgende keer!", "Until next time!"],
]},
{ name: "Getting around", emoji: "🚋", cards: [
  ["Excuseer, waar is het station?", "Excuse me, where is the station?", "'Excuseer' is the Flemish 'excuse me'"],
  ["Hoe kom ik naar het centrum?", "How do I get to the centre?"],
  ["Is het ver?", "Is it far?"],
  ["Is het hier dichtbij?", "Is it close by?"],
  ["Ga rechtdoor.", "Go straight on.", "👂"],
  ["Sla linksaf.", "Turn left.", "👂"],
  ["Sla rechtsaf.", "Turn right.", "👂"],
  ["aan de overkant", "on the other side"],
  ["op de hoek", "on the corner"],
  ["de tram", "the tram"],
  ["de bus", "the bus"],
  ["de trein", "the train"],
  ["de fiets", "the bike"],
  ["Welke tram gaat naar het station?", "Which tram goes to the station?"],
  ["Waar is de halte?", "Where is the stop?"],
  ["Waar moet ik uitstappen?", "Where do I need to get off?"],
  ["Een ticket naar Brussel, alstublieft.", "A ticket to Brussels, please."],
  ["Enkele reis of heen en terug?", "Single or return?", "👂"],
  ["Hoe laat vertrekt de trein?", "What time does the train leave?"],
  ["Van welk spoor vertrekt de trein?", "Which platform does the train leave from?"],
  ["De trein heeft vertraging.", "The train is delayed.", "👂"],
  ["Is deze plaats vrij?", "Is this seat free?"],
  ["Mag ik er even door?", "Can I get past, please?"],
]},
{ name: "Doctor & pharmacy", emoji: "💊", cards: [
  ["Ik voel me niet goed.", "I don't feel well."],
  ["Ik ben ziek.", "I'm sick."],
  ["Ik heb hoofdpijn.", "I have a headache."],
  ["Ik heb buikpijn.", "I have a stomach ache."],
  ["Ik heb keelpijn.", "I have a sore throat."],
  ["Ik heb koorts.", "I have a fever."],
  ["Ik ben verkouden.", "I have a cold."],
  ["Ik moet veel hoesten.", "I'm coughing a lot."],
  ["Ik ben duizelig.", "I feel dizzy."],
  ["Ik wil een afspraak maken bij de dokter.", "I'd like to make an appointment with the doctor."],
  ["Waar doet het pijn?", "Where does it hurt?", "👂 Doctor question"],
  ["Het doet hier pijn.", "It hurts here."],
  ["Sinds wanneer heeft u dit?", "Since when have you had this?", "👂 Doctor question"],
  ["Sinds gisteren.", "Since yesterday."],
  ["Ik heb een ziektebriefje nodig voor mijn werk.", "I need a sick note for my work.", "Belgian: 'ziektebriefje' = doctor's sick note"],
  ["Heeft u iets tegen hoofdpijn?", "Do you have something for a headache?"],
  ["Heeft u een voorschrift?", "Do you have a prescription?", "👂 At the pharmacy"],
  ["Hoe vaak moet ik dit nemen?", "How often do I need to take this?"],
  ["Drie keer per dag.", "Three times a day.", "👂"],
  ["de apotheek", "the pharmacy"],
]},
{ name: "City hall, bank & post", emoji: "🏛️", cards: [
  ["Ik wil me inschrijven bij de gemeente.", "I'd like to register with the municipality."],
  ["Ik heb een afspraak om tien uur.", "I have an appointment at ten o'clock."],
  ["Neem een nummertje.", "Take a number.", "👂 For the queue"],
  ["Welke documenten heb ik nodig?", "Which documents do I need?"],
  ["Hier is mijn identiteitskaart.", "Here is my ID card."],
  ["Hier is mijn paspoort.", "Here is my passport."],
  ["Ik heb mijn huurcontract bij me.", "I have my rental contract with me."],
  ["Wat is uw adres?", "What's your address?", "👂"],
  ["Uw geboortedatum, alstublieft.", "Your date of birth, please.", "👂"],
  ["Wat is uw rijksregisternummer?", "What's your national register number?", "👂 The number on the back of a Belgian ID card"],
  ["Moet ik een formulier invullen?", "Do I need to fill in a form?"],
  ["Kunt u mij helpen met dit formulier?", "Can you help me with this form?"],
  ["Waar moet ik tekenen?", "Where do I need to sign?"],
  ["Wanneer is mijn kaart klaar?", "When will my card be ready?"],
  ["Ik wil een rekening openen.", "I'd like to open an account."],
  ["Mijn kaart werkt niet.", "My card doesn't work."],
  ["Ik wil een pakje versturen.", "I'd like to send a parcel."],
  ["Ik kom een pakje ophalen.", "I'm here to pick up a parcel."],
]},
{ name: "Phone & appointments", emoji: "📞", cards: [
  ["Hallo, met wie spreek ik?", "Hello, who am I speaking to?"],
  ["Met Alex.", "It's Alex speaking.", "How Belgians answer the phone — use your own name"],
  ["Ik bel over mijn afspraak.", "I'm calling about my appointment."],
  ["Kan ik een afspraak maken?", "Can I make an appointment?"],
  ["Past dinsdag om tien uur?", "Does Tuesday at ten work?"],
  ["Dat past.", "That works."],
  ["Dat past niet, sorry.", "That doesn't work, sorry."],
  ["Kan het iets later?", "Can it be a bit later?"],
  ["Kan het vroeger?", "Can it be earlier?"],
  ["Kan ik mijn afspraak verplaatsen?", "Can I reschedule my appointment?"],
  ["Ik moet mijn afspraak annuleren.", "I need to cancel my appointment."],
  ["Wat is uw telefoonnummer?", "What's your phone number?", "👂"],
  ["Kunt u mij terugbellen?", "Can you call me back?"],
  ["Ik hoor u slecht.", "I can't hear you well."],
  ["Ik stuur je een berichtje.", "I'll send you a message."],
]},
{ name: "Home & housing", emoji: "🏠", cards: [
  ["Ik woon op kot.", "I live in a student room.", "Flemish: 'kot' = student room"],
  ["Ik zoek een appartement.", "I'm looking for a flat."],
  ["Hoeveel is de huur?", "How much is the rent?"],
  ["Zijn de kosten inbegrepen?", "Are the utilities included?"],
  ["Wanneer kan ik de kamer bekijken?", "When can I view the room?"],
  ["De verwarming werkt niet.", "The heating doesn't work."],
  ["Er is geen warm water.", "There's no hot water."],
  ["De wifi werkt niet.", "The wifi doesn't work."],
  ["Er is een lek.", "There's a leak."],
  ["Kunt u dat komen herstellen?", "Can you come and fix that?", "Flemish: 'herstellen' = repair"],
  ["Ik ben mijn sleutel vergeten.", "I forgot my key."],
  ["Wanneer wordt het afval opgehaald?", "When is the rubbish collected?"],
  ["Wie doet de afwas?", "Who's doing the dishes?"],
  ["Kun je wat stiller zijn?", "Can you be a bit quieter?"],
  ["de huisbaas", "the landlord"],
  ["de sleutel", "the key"],
  ["de keuken", "the kitchen"],
  ["de badkamer", "the bathroom"],
  ["de slaapkamer", "the bedroom"],
]},
{ name: "School", emoji: "🎒", cards: [
  ["Waar is het lokaal?", "Where is the classroom?"],
  ["Hoe laat begint de les?", "What time does the class start?"],
  ["Ik ben te laat, sorry.", "I'm late, sorry."],
  ["Mag ik een vraag stellen?", "May I ask a question?"],
  ["Ik heb een vraag.", "I have a question."],
  ["Wanneer is de deadline?", "When is the deadline?"],
  ["Wanneer is het examen?", "When is the exam?"],
  ["Waar kan ik dat vinden?", "Where can I find that?"],
  ["Kun je me helpen?", "Can you help me?"],
  ["Zullen we samenwerken?", "Shall we work together?"],
  ["Wanneer heb je tijd?", "When do you have time?"],
  ["Ik begrijp de opdracht niet.", "I don't understand the assignment."],
  ["Mag ik je notities lenen?", "Can I borrow your notes?"],
  ["Ik ben klaar.", "I'm done."],
  ["Ik heb pauze.", "I'm on a break."],
  ["Tot morgen!", "See you tomorrow!"],
]},
{ name: "Emergencies", emoji: "🚨", cards: [
  ["Help!", "Help!"],
  ["Ik heb hulp nodig.", "I need help."],
  ["Bel een ambulance!", "Call an ambulance!"],
  ["Bel de politie!", "Call the police!"],
  ["Bel honderdtwaalf!", "Call 112!", "112 is the emergency number in Belgium"],
  ["Brand!", "Fire!"],
  ["Er is een ongeluk gebeurd.", "There's been an accident."],
  ["Gaat het?", "Are you OK?"],
  ["Het is dringend.", "It's urgent."],
  ["Ik ben gewond.", "I'm injured."],
  ["Ik heb een dokter nodig.", "I need a doctor."],
  ["Waar is het ziekenhuis?", "Where is the hospital?"],
  ["Ik ben bestolen.", "I've been robbed."],
  ["Ik ben mijn portefeuille kwijt.", "I've lost my wallet."],
  ["Ik ben mijn gsm kwijt.", "I've lost my phone.", "Flemish: 'gsm' = mobile phone"],
  ["Ik ben verdwaald.", "I'm lost."],
]},
{ name: "Essentials", emoji: "⭐", cards: [
  ["ja", "yes"],
  ["nee", "no"],
  ["alstublieft", "please / here you are (formal)"],
  ["alsjeblieft", "please / here you are (informal)"],
  ["dank u", "thank you (formal)"],
  ["dank je", "thank you (informal)"],
  ["merci", "thanks", "Borrowed from French — very common in Flanders"],
  ["graag gedaan", "you're welcome"],
  ["sorry", "sorry"],
  ["excuseer", "excuse me"],
  ["Geen probleem.", "No problem."],
  ["Oké, prima.", "OK, fine."],
  ["Ik weet het niet.", "I don't know."],
  ["Mag ik iets vragen?", "May I ask something?"],
  ["Waar is het toilet?", "Where is the toilet?"],
  ["wat", "what"],
  ["wie", "who"],
  ["waar", "where"],
  ["wanneer", "when"],
  ["waarom", "why"],
  ["hoe", "how"],
  ["hier", "here"],
  ["daar", "there"],
  ["nu", "now"],
  ["straks", "later (today)"],
  ["misschien", "maybe"],
  ["altijd", "always"],
  ["nooit", "never"],
]},
{ name: "Numbers & days", emoji: "🔢", cards: [
  ["één", "one"], ["twee", "two"], ["drie", "three"], ["vier", "four"], ["vijf", "five"],
  ["zes", "six"], ["zeven", "seven"], ["acht", "eight"], ["negen", "nine"], ["tien", "ten"],
  ["elf", "eleven"], ["twaalf", "twelve"], ["dertien", "thirteen"], ["veertien", "fourteen"], ["vijftien", "fifteen"],
  ["zestien", "sixteen"], ["zeventien", "seventeen"], ["achttien", "eighteen"], ["negentien", "nineteen"], ["twintig", "twenty"],
  ["vijfentwintig", "twenty-five", "Dutch says 'five-and-twenty'"],
  ["dertig", "thirty"], ["veertig", "forty"], ["vijftig", "fifty"], ["zestig", "sixty"],
  ["zeventig", "seventy"], ["tachtig", "eighty"], ["negentig", "ninety"], ["honderd", "a hundred"],
  ["vijf euro vijftig", "five euros fifty", "👂 How prices are said"],
  ["maandag", "Monday"], ["dinsdag", "Tuesday"], ["woensdag", "Wednesday"], ["donderdag", "Thursday"],
  ["vrijdag", "Friday"], ["zaterdag", "Saturday"], ["zondag", "Sunday"],
  ["vandaag", "today"], ["morgen", "tomorrow"], ["gisteren", "yesterday"],
  ["het weekend", "the weekend"], ["volgende week", "next week"], ["vanavond", "tonight"],
  ["Hoe laat is het?", "What time is it?"],
  ["Het is drie uur.", "It's three o'clock."],
  ["om acht uur", "at eight o'clock"],
  ["half drie", "half past two (2:30)", "Careful: 'half drie' = half TO three"],
  ["kwart over vier", "quarter past four"],
  ["kwart voor vijf", "quarter to five"],
]},
];
