// Situation-based deck. Each card: [dutch, english, note?]
// A note starting with "👂" marks something you'll HEAR (so you recognise it), not something you say.
const CATEGORIES = [
{ name: "Meeting someone", emoji: "👋", cards: [
  ["Hallo! / Hoi!", "Hello! / Hi!"],
  ["Hoe heet je?", "What's your name?"],
  ["Ik heet …", "My name is …"],
  ["Aangenaam!", "Nice to meet you!"],
  ["Hoe gaat het (met je)?", "How are you?"],
  ["Goed, en met jou?", "Good, and you?"],
  ["Waar kom je vandaan?", "Where are you from?"],
  ["Ik kom uit …", "I'm from …"],
  ["Waar woon je?", "Where do you live?"],
  ["Ik woon in Antwerpen.", "I live in Antwerp."],
  ["Wat doe je?", "What do you do (for a living)?"],
  ["Ik ben student.", "I'm a student."],
  ["Ik studeer aan de KdG.", "I study at KdG."],
  ["Hoe oud ben je?", "How old are you?"],
  ["Ik ben … jaar oud.", "I'm … years old."],
  ["Spreek je Engels?", "Do you speak English?"],
  ["Ik leer Nederlands.", "I'm learning Dutch."],
  ["Ik spreek een beetje Nederlands.", "I speak a little Dutch."],
  ["Je Nederlands is goed!", "Your Dutch is good!", "👂 You'll hear this — say 'Dank je!'"],
  ["Tot ziens! / Tot later!", "Goodbye! / See you later!"],
  ["Ça va?", "How's it going?", "Common in Flanders, borrowed from French"],
]},
{ name: "Small talk", emoji: "💬", cards: [
  ["Wat een mooi weer, hè!", "What nice weather, huh!"],
  ["Het regent weer.", "It's raining again."],
  ["Het is koud vandaag.", "It's cold today."],
  ["Wat ga je dit weekend doen?", "What are you doing this weekend?"],
  ["Heb je een leuk weekend gehad?", "Did you have a nice weekend?"],
  ["Wat zijn je hobby's?", "What are your hobbies?"],
  ["Ik hou van sporten.", "I like doing sports."],
  ["Ik hou van muziek.", "I love music."],
  ["Heb je zin om iets te drinken?", "Do you feel like getting a drink?"],
  ["Goed idee!", "Good idea!"],
  ["Dat is leuk!", "That's nice / fun!"],
  ["Echt?", "Really?"],
  ["Zeker!", "Definitely!"],
  ["Geen idee.", "No idea."],
  ["Mag ik je nummer?", "Can I have your number?"],
  ["Tot de volgende keer!", "Until next time!"],
]},
{ name: "Understanding", emoji: "🤔", cards: [
  ["Sorry, ik begrijp het niet.", "Sorry, I don't understand."],
  ["Kun je dat herhalen?", "Can you repeat that?"],
  ["Kun je langzamer praten?", "Can you speak more slowly?"],
  ["Wat betekent …?", "What does … mean?"],
  ["Hoe zeg je … in het Nederlands?", "How do you say … in Dutch?"],
  ["Hoe spel je dat?", "How do you spell that?"],
  ["Kun je dat opschrijven?", "Can you write that down?"],
  ["Ik ben nog aan het leren.", "I'm still learning."],
  ["Een momentje, alsjeblieft.", "One moment, please."],
  ["Wablieft?", "Pardon? / Come again?", "Very Flemish — you'll hear it a lot"],
]},
{ name: "Shop", emoji: "🛍️", cards: [
  ["Goedendag!", "Good day!", "Standard Flemish greeting entering a shop"],
  ["Kan ik u helpen?", "Can I help you?", "👂 Shop staff will ask this"],
  ["Ik kijk gewoon even rond.", "I'm just looking around."],
  ["Ik zoek …", "I'm looking for …"],
  ["Heeft u dit in een andere maat?", "Do you have this in another size?"],
  ["Heeft u dit in een andere kleur?", "Do you have this in another colour?"],
  ["Mag ik dit passen?", "Can I try this on?"],
  ["Waar zijn de paskamers?", "Where are the fitting rooms?"],
  ["Het is te groot / te klein.", "It's too big / too small."],
  ["Hoeveel kost dit?", "How much does this cost?"],
  ["Dat is te duur.", "That's too expensive."],
  ["Ik neem het.", "I'll take it."],
  ["Mag ik met de kaart betalen?", "Can I pay by card?"],
  ["Contactloos, alstublieft.", "Contactless, please."],
  ["Wilt u een zakje?", "Would you like a bag?", "👂 Cashier question"],
  ["Nee, dank u, ik heb een tas.", "No thanks, I have a bag."],
  ["Wilt u het ticketje?", "Do you want the receipt?", "👂 'ticketje' = receipt in Flanders"],
  ["Mag ik dit ruilen?", "Can I exchange this?"],
  ["Nog een prettige dag!", "Have a nice day!"],
]},
{ name: "Supermarket", emoji: "🛒", cards: [
  ["Waar vind ik de melk?", "Where can I find the milk?"],
  ["Waar is …?", "Where is …?"],
  ["Heeft u nog …?", "Do you still have …?"],
  ["Is dit in promotie?", "Is this on offer?", "Flemish: 'promotie' = sale/offer"],
  ["het brood", "the bread"],
  ["de kaas", "the cheese"],
  ["de groenten", "the vegetables"],
  ["het fruit", "the fruit"],
  ["het vlees", "the meat"],
  ["de eieren", "the eggs"],
  ["de kassa", "the checkout"],
  ["een winkelkar", "a shopping trolley"],
  ["Heeft u een klantenkaart?", "Do you have a loyalty card?", "👂 Cashier question"],
  ["Nee, die heb ik niet.", "No, I don't have one."],
]},
{ name: "Bakery", emoji: "🥖", cards: [
  ["Wie is er aan de beurt?", "Who's next?", "👂 Staff calling the next customer"],
  ["Ik ben aan de beurt.", "It's my turn."],
  ["Een wit brood, alstublieft.", "A white bread, please."],
  ["Gesneden, alstublieft.", "Sliced, please."],
  ["Twee pistolets, alstublieft.", "Two bread rolls, please.", "Flemish: 'pistolet' = round crusty roll"],
  ["Een croissant, alstublieft.", "A croissant, please."],
  ["Mag het iets meer zijn?", "Anything else?", "👂 Literally 'May it be a bit more?'"],
  ["Nee, dat is alles.", "No, that's everything."],
  ["Dat is alles, dank u.", "That's all, thank you."],
]},
{ name: "Café & restaurant", emoji: "🍽️", cards: [
  ["Een tafel voor twee, alstublieft.", "A table for two, please."],
  ["Heeft u een reservatie?", "Do you have a reservation?", "👂 Flemish: 'reservatie'"],
  ["Ik heb gereserveerd op naam van …", "I have a reservation under the name …"],
  ["Mag ik de kaart, alstublieft?", "Can I have the menu, please?"],
  ["Wat wilt u drinken?", "What would you like to drink?", "👂 Waiter question"],
  ["Ik wil graag een cola.", "I'd like a cola."],
  ["Een pintje, alstublieft.", "A beer (small draught), please.", "Flemish: 'pintje' = glass of lager"],
  ["Een kraantjeswater, alstublieft.", "A tap water, please."],
  ["Plat of bruis?", "Still or sparkling?", "👂 About water"],
  ["Wat raadt u aan?", "What do you recommend?"],
  ["Ik neem …", "I'll have …"],
  ["Ik ben vegetariër.", "I'm vegetarian."],
  ["Ik ben allergisch voor …", "I'm allergic to …"],
  ["Zit er … in?", "Is there … in it?"],
  ["Alles in orde?", "Is everything OK?", "👂 Waiter checking on you"],
  ["Het is heel lekker!", "It's very tasty!"],
  ["Eet smakelijk!", "Enjoy your meal!"],
  ["Mag ik de rekening, alstublieft?", "Can I have the bill, please?"],
  ["Samen of apart?", "Together or separately?", "👂 About paying"],
  ["Apart, alstublieft.", "Separately, please."],
  ["Laat maar zitten.", "Keep the change."],
]},
{ name: "Getting around", emoji: "🚋", cards: [
  ["Excuseer, waar is het station?", "Excuse me, where is the station?", "'Excuseer' is the Flemish 'excuse me'"],
  ["Hoe kom ik naar …?", "How do I get to …?"],
  ["Is het ver?", "Is it far?"],
  ["Ga rechtdoor.", "Go straight on.", "👂"],
  ["Sla linksaf / rechtsaf.", "Turn left / right.", "👂"],
  ["aan de overkant", "on the other side"],
  ["de tram / de bus / de trein", "the tram / the bus / the train"],
  ["Welke tram gaat naar …?", "Which tram goes to …?"],
  ["Waar is de halte?", "Where is the stop?"],
  ["Een ticket naar …, alstublieft.", "A ticket to …, please."],
  ["Enkel of heen en terug?", "Single or return?", "👂"],
  ["Hoe laat vertrekt de trein?", "What time does the train leave?"],
  ["Van welk spoor?", "From which platform?"],
  ["Is deze plaats vrij?", "Is this seat free?"],
  ["de fiets", "the bike"],
]},
{ name: "Doctor & pharmacy", emoji: "💊", cards: [
  ["Ik voel me niet goed.", "I don't feel well."],
  ["Ik ben ziek.", "I'm sick."],
  ["Ik heb hoofdpijn.", "I have a headache."],
  ["Ik heb buikpijn.", "I have a stomach ache."],
  ["Ik heb keelpijn.", "I have a sore throat."],
  ["Ik heb koorts.", "I have a fever."],
  ["Ik ben verkouden.", "I have a cold."],
  ["Ik wil een afspraak maken.", "I'd like to make an appointment."],
  ["Heeft u iets tegen …?", "Do you have something for …?"],
  ["Hoe vaak moet ik dit nemen?", "How often do I need to take this?"],
  ["Heeft u een voorschrift?", "Do you have a prescription?", "👂 At the pharmacy (apotheek)"],
  ["Waar doet het pijn?", "Where does it hurt?", "👂 Doctor question"],
]},
{ name: "School & work", emoji: "🎒", cards: [
  ["Waar is lokaal …?", "Where is classroom …?"],
  ["Hoe laat begint de les?", "What time does the class start?"],
  ["Ik ben te laat, sorry.", "I'm late, sorry."],
  ["Mag ik een vraag stellen?", "May I ask a question?"],
  ["Ik heb een vraag.", "I have a question."],
  ["Wanneer is de deadline?", "When is the deadline?"],
  ["Kun je me helpen?", "Can you help me?"],
  ["Zullen we samenwerken?", "Shall we work together?"],
  ["Ik ben klaar.", "I'm done."],
  ["Wanneer heb je tijd?", "When do you have time?"],
  ["Ik heb het druk.", "I'm busy."],
  ["Ik heb pauze.", "I'm on a break."],
  ["Tot morgen!", "See you tomorrow!"],
]},
{ name: "Phone & appointments", emoji: "📞", cards: [
  ["Met … (spreekt u).", "This is … (speaking).", "How Belgians answer the phone"],
  ["Ik bel over …", "I'm calling about …"],
  ["Kan ik een afspraak maken?", "Can I make an appointment?"],
  ["Past dinsdag om tien uur?", "Does Tuesday at ten work?"],
  ["Dat past.", "That works."],
  ["Dat past niet, sorry.", "That doesn't work, sorry."],
  ["Kan het later?", "Can it be later?"],
  ["Ik moet mijn afspraak annuleren.", "I need to cancel my appointment."],
  ["Kunt u mij terugbellen?", "Can you call me back?"],
  ["Mijn nummer is …", "My number is …"],
]},
{ name: "Emergencies", emoji: "🚨", cards: [
  ["Help!", "Help!"],
  ["Bel een ambulance!", "Call an ambulance!"],
  ["Bel de politie!", "Call the police!"],
  ["Ik ben mijn portefeuille kwijt.", "I've lost my wallet."],
  ["Ik ben mijn gsm kwijt.", "I've lost my phone.", "Flemish: 'gsm' = mobile phone"],
  ["Ik ben verdwaald.", "I'm lost."],
  ["Waar is het ziekenhuis?", "Where is the hospital?"],
  ["Het is dringend.", "It's urgent."],
]},
{ name: "Essentials", emoji: "⭐", cards: [
  ["ja / nee", "yes / no"],
  ["alstublieft", "please (formal) / here you are"],
  ["alsjeblieft", "please (informal) / here you are"],
  ["dank u / dank je", "thank you (formal / informal)"],
  ["graag gedaan", "you're welcome"],
  ["sorry / excuseer", "sorry / excuse me"],
  ["Geen probleem.", "No problem."],
  ["Oké, prima.", "OK, fine."],
  ["Ik weet het niet.", "I don't know."],
  ["Ik wil graag …", "I would like …"],
  ["Mag ik …?", "May I …?"],
  ["Waar is het toilet?", "Where is the toilet?"],
  ["Hoe laat is het?", "What time is it?"],
  ["vandaag / morgen / gisteren", "today / tomorrow / yesterday"],
]},
{ name: "Numbers & days", emoji: "🔢", cards: [
  ["een, twee, drie", "one, two, three"],
  ["vier, vijf, zes", "four, five, six"],
  ["zeven, acht, negen, tien", "seven, eight, nine, ten"],
  ["elf, twaalf", "eleven, twelve"],
  ["twintig", "twenty"],
  ["vijfentwintig", "twenty-five", "Dutch says 'five-and-twenty'"],
  ["honderd", "hundred"],
  ["vijf euro vijftig", "five euros fifty", "👂 How prices are said"],
  ["maandag, dinsdag, woensdag", "Monday, Tuesday, Wednesday"],
  ["donderdag, vrijdag", "Thursday, Friday"],
  ["zaterdag, zondag", "Saturday, Sunday"],
  ["het weekend", "the weekend"],
  ["half drie", "half past two (2:30)", "Careful: 'half drie' = half TO three"],
  ["kwart over vier", "quarter past four"],
]},
];
