// Explanations shown with each card: word-by-word glosses, literal translations and grammar tips.

// Short gloss for every word in the deck. Verb forms name their infinitive in brackets.
const GLOSS = {
  "aan":"on / at","aangenaam":"pleasant","aardappel":"potato","aardappelen":"potatoes","acht":"eight","achter":"behind",
  "achttien":"eighteen","adres":"address","af":"off (verb part)","afspraak":"appointment","afspreken":"to arrange to meet",
  "afval":"rubbish","afwas":"washing-up","ah":"ah","al":"already","alex":"Alex (name)","allemaal":"all / everyone",
  "allergisch":"allergic","alles":"everything","alsjeblieft":"please (informal)","alstublieft":"please (formal)",
  "altijd":"always","ambulance":"ambulance","andere":"other","anders":"else / different","annuleren":"to cancel",
  "antwerpen":"Antwerp","apart":"separate(ly)","apotheek":"pharmacy","appartement":"flat / apartment","baas":"boss",
  "badkamer":"bathroom","bakken":"to fry / to bake","bedankt":"thanks","bedoel":"mean (bedoelen)","beetje":"little bit",
  "begin":"start (beginnen)","begint":"starts (beginnen)","begrijp":"understand (begrijpen)","bekijken":"to look at / view",
  "bel":"call (bellen)","ben":"am / are (zijn)","bent":"are (zijn)","berichtje":"little message","best":"best",
  "bestek":"cutlery","bestelling":"order","bestolen":"robbed (bestelen)","betalen":"to pay","betekent":"means (betekenen)",
  "beterschap":"get-well wish","beurt":"turn","bij":"with / at / extra","bijna":"almost","blij":"happy",
  "blokjes":"little cubes","bon":"order ticket","bord":"plate","boter":"butter","brand":"fire","broer":"brother",
  "broers":"brothers","brood":"bread / loaf","bruin":"brown","bruis":"sparkling","brussel":"Brussels",
  "buikpijn":"belly-pain","bus":"bus","cadeau":"present","cash":"cash","centrum":"centre","chef":"chef","code":"code / PIN",
  "cola":"cola","collega":"colleague","contactloos":"contactless","croissant":"croissant","daag":"bye","daar":"there",
  "dag":"day","dagschotel":"day-dish","dan":"then","dank":"thanks","dat":"that","de":"the","deadline":"deadline",
  "denk":"think (denken)","dertien":"thirteen","dertig":"thirty","deze":"this / these","dichtbij":"close by",
  "die":"that / those","diepvries":"freezer (deep-freeze)","dinsdag":"Tuesday","dit":"this","documenten":"documents",
  "doe":"do (doen)","doen":"to do","doet":"does (doen)","dokter":"doctor","donderdag":"Thursday","door":"through",
  "dorst":"thirst","drie":"three","dringend":"urgent","drink":"drink (drinken)","drinken":"to drink","druk":"busy",
  "duizelig":"dizzy","duur":"expensive","duurt":"lasts / takes (duren)","dweilen":"to mop","echt":"really","een":"a / one",
  "eens":"once / just (softener)","eerst":"first","eet":"eat (eten)","eieren":"eggs","elf":"eleven","en":"and",
  "engels":"English","enkele":"single","er":"there / of it","eten":"to eat / food","euro":"euro","even":"just / quickly",
  "examen":"exam","excuseer":"excuse (me)","extra":"extra","fiets":"bike","fijne":"nice","films":"films",
  "formulier":"form","friet":"fries","frigo":"fridge","friteuse":"deep fryer","frituren":"to deep-fry","fruit":"fruit",
  "ga":"go (gaan)","gaar":"cooked through","gaat":"goes (gaan)","gebeurd":"happened (gebeuren)",
  "geboortedatum":"birth-date","gedaan":"done (doen)","geduld":"patience","geen":"no / not a","gehad":"had (hebben)",
  "gelukt":"succeeded (lukken)","gemeente":"municipality","gepast":"exact (fitting)","gereserveerd":"reserved (reserveren)",
  "gerust":"without worry / freely","gesneden":"cut (snijden)","gewerkt":"worked (werken)","gewond":"injured",
  "gewoon":"just / simply","gezellig":"cosy / sociable","gisteren":"yesterday","gluten":"gluten","goed":"good / well",
  "goedendag":"good day","goeiemorgen":"good morning","graag":"gladly","graden":"degrees","groenten":"vegetables",
  "groot":"big","grote":"big","gsm":"mobile phone","haal":"fetch (halen)","half":"half","hallo":"hello","halte":"stop",
  "handen":"hands","handschoenen":"gloves (hand-shoes)","heb":"have (hebben)","hebben":"to have","heeft":"has (hebben)",
  "heel":"very / whole","heen":"there (going)","heet":"is called (heten) / hot","help":"help","helpen":"to help",
  "herhalen":"to repeat","herstellen":"to repair","het":"it / the","hier":"here","hobby's":"hobbies","hoe":"how",
  "hoek":"corner","hoesten":"to cough","hoeveel":"how much / many","hoi":"hi","honderd":"hundred",
  "honderdtwaalf":"hundred-twelve","honger":"hunger","hoofdpijn":"head-pain","hoor":"hear (horen)",
  "hou":"hold (houden)","huis":"house / home","huisbaas":"landlord (house-boss)","hulp":"help","huur":"rent",
  "huurcontract":"rental contract","hè":"huh / right?","idee":"idea","identiteitskaart":"identity card",
  "iemand":"someone","iets":"something","ik":"I","in":"in","inbegrepen":"included","inschrijven":"to register (in-write)",
  "insteken":"to insert (in-stick)","invullen":"to fill in","is":"is","ja":"yes","jaar":"year(s)","jammer":"pity",
  "jas":"coat","je":"you / your (informal)","jou":"you (informal)","juist":"right / correct","kaart":"card / menu",
  "kaas":"cheese","kamer":"room","kan":"can (kunnen)","kassa":"till / checkout","kdg":"KdG (university college)",
  "keelpijn":"throat-pain","keer":"time(s)","keuken":"kitchen","kijk":"look (kijken)","kip":"chicken","klaar":"ready / done",
  "klantenkaart":"customer card","klein":"small","kleine":"small","kleur":"colour","klopt":"is right (kloppen)",
  "koekenpan":"frying pan","koffie":"coffee","koffiekoeken":"coffee-cakes (pastries)","koken":"to cook / boil",
  "kom":"come (komen)","komen":"to come","kook":"cook (koken)","kookpot":"cooking pot","koorts":"fever",
  "korting":"discount","kost":"costs (kosten)","kosten":"costs / bills","kot":"student room","koud":"cold",
  "kraantjeswater":"little-tap water","krijgen":"to get","kruiden":"herbs / spices","kun":"can (kunnen)",
  "kunt":"can (kunnen)","kwart":"quarter","kwijt":"lost / gone","laat":"late / let (laten)","lang":"long",
  "langzamer":"slower","later":"later","leer":"learn (leren)","lek":"leak","lekker":"tasty / nice","lenen":"to borrow",
  "leren":"(to) learn","les":"lesson / class","leuk":"nice / fun","liggen":"lie (be lying)","linksaf":"to the left",
  "lokaal":"classroom","loon":"pay / wage","loonbrief":"pay-letter (payslip)","maak":"make (maken)",
  "maakt":"makes (maken)","maandag":"Monday","maar":"but / just","maat":"size","mag":"may (mogen)","maken":"to make",
  "mandje":"little basket","mayonaise":"mayonnaise","me":"me / myself","mee":"along","meer":"more","melk":"milk",
  "merci":"thanks (from French)","mes":"knife","met":"with","mij":"me","mijn":"my","minuten":"minutes",
  "misschien":"maybe","mist":"is missing (missen)","moe":"tired","moet":"must (moeten)","momentje":"little moment",
  "mooi":"beautiful / nice","morgen":"tomorrow / morning","muziek":"music","na":"after (verb part)","naam":"name",
  "naar":"to / towards","nederlands":"Dutch","nee":"no","neem":"take (nemen)","negen":"nine","negentien":"nineteen",
  "negentig":"ninety","nemen":"to take","niet":"not","nodig":"needed","nog":"still / yet / another","nooit":"never",
  "noten":"nuts","notities":"notes","nu":"now","nummer":"number","nummertje":"little number","of":"or","oké":"OK",
  "om":"at / in order to","ongeluk":"accident (un-luck)","ongeveer":"about / roughly","ontmoeten":"to meet",
  "ook":"also / too","op":"on / up / used up","opdracht":"assignment","open":"open","openen":"to open",
  "opgehaald":"collected (ophalen)","ophalen":"to pick up","opnieuw":"again (anew)","opschrijven":"to write down",
  "orde":"order","oud":"old","oven":"oven","over":"about / past / over","overkant":"other side","pakje":"little package",
  "pan":"pan","pas":"watch (oppassen)","paskamers":"fitting rooms (try-rooms)","paspoort":"passport",
  "passen":"to try on / to fit","past":"fits (passen)","pauze":"break","peeters":"Peeters (surname)","per":"per",
  "pijn":"pain","pikant":"spicy","pintje":"little pint (beer)","pistolets":"bread rolls","plaats":"place / seat",
  "plakjes":"little slices","plat":"flat (still)","politie":"police","portefeuille":"wallet","porties":"portions",
  "praten":"to talk","prettige":"pleasant","prima":"fine","proberen":"to try","probleem":"problem","proef":"taste (proeven)",
  "proficiat":"congratulations","promotie":"special offer","proper":"clean","raadt":"advises (aanraden)",
  "rechtdoor":"straight on","rechtsaf":"to the right","reepjes":"little strips","regent":"rains (regenen)",
  "reis":"journey","rekening":"bill / account","reservatie":"reservation","restaurant":"restaurant",
  "rijksregisternummer":"national register number","rijst":"rice","roep":"call (roepen)","rond":"around",
  "ruilen":"to exchange","samen":"together","samenwerken":"to work together","saus":"sauce","schil":"peel (schillen)",
  "schol":"cheers","schort":"apron","shift":"shift","sinds":"since","sla":"turn / hit (slaan)","slaapkamer":"bedroom (sleep-room)",
  "slecht":"bad(ly)","sleutel":"key","sluit":"closes (sluiten)","smakelijk":"tasty / tastily","snij":"cut (snijden)",
  "snijden":"to cut","snijplank":"cutting board (cut-plank)","soep":"soup","sorry":"sorry","spaghetti":"spaghetti",
  "spanje":"Spain","spel":"spell (spellen)","spijtig":"regrettable / a pity","spoor":"track / platform",
  "sporten":"doing sports","spreek":"speak (spreken)","spreken":"to speak","staat":"stands (staan)","stad":"town / city",
  "station":"station","stellen":"to put / to ask (a question)","stiller":"quieter","stop":"stop (stoppen)",
  "straks":"later on","studeer":"study (studeren)","student":"student","stuur":"send (sturen)","succes":"success / luck",
  "tachtig":"eighty","tafel":"table","tas":"bag","te":"too / to","tegen":"against / for","tekenen":"to sign / draw",
  "telefoonnummer":"phone number","terug":"back","terugbellen":"to call back","terugbrengen":"to bring back",
  "ticket":"ticket","ticketje":"little ticket (receipt)","tien":"ten","tijd":"time","toilet":"toilet","tomaat":"tomato",
  "tomaten":"tomatoes","tot":"until","trakteer":"treat (trakteren)","tram":"tram","trein":"train","twaalf":"twelve",
  "twee":"two","tweehonderd":"two hundred","twintig":"twenty","u":"you (formal)","ui":"onion","uien":"onions",
  "uit":"out / from","uitstappen":"to get off (out-step)","uren":"hours","uur":"hour / o'clock",
  "uurrooster":"schedule (hour-schedule)","uw":"your (formal)","vaak":"often","van":"of / from","vanavond":"tonight",
  "vandaag":"today","vandaan":"from","veel":"a lot / much","veertien":"fourteen","veertig":"forty",
  "vegetarisch":"vegetarian","vegetariër":"a vegetarian","ver":"far","verbandkist":"first-aid kit (bandage-chest)",
  "verbeter":"correct (verbeteren)","verbrand":"burnt (verbranden)","verdwaald":"lost (verdwalen)",
  "vergeten":"forgotten (vergeten)","verkouden":"having a cold","verplaatsen":"to move","versturen":"to send",
  "vertraging":"delay","vertrekt":"leaves (vertrekken)","verwarming":"heating","vier":"four","vijf":"five",
  "vijfentwintig":"five-and-twenty","vijftien":"fifteen","vijftig":"fifty","vind":"find / think (vinden)",
  "vinden":"to find","vis":"fish","vlees":"meat","vloer":"floor","voel":"feel (voelen)","volgende":"next (following)",
  "voor":"for / before","voorschrift":"prescription","vraag":"ask (vragen) / question","vragen":"to ask","vrij":"free",
  "vrijdag":"Friday","vroeger":"earlier","waar":"where","waarom":"why","wablieft":"pardon? (what-please)",
  "wanneer":"when","warm":"warm","was":"wash (wassen) / was","wat":"what / some","water":"water","we":"we",
  "week":"week","weekend":"weekend","weer":"again / weather","weet":"know (weten)","wel":"indeed (affirms)",
  "welk":"which","welke":"which","werk":"work","werken":"to work","werkplek":"workplace (work-spot)",
  "werkt":"works (werken)","wie":"who","wifi":"wifi","wil":"want (willen)","wilt":"want (willen)",
  "winkelkar":"shopping trolley (shop-cart)","wisselen":"to swap","wisselgeld":"change (swap-money)","wit":"white",
  "woensdag":"Wednesday","woon":"live (wonen)","woord":"word","wordt":"becomes / is being (worden)",
  "zakje":"little bag","zaterdag":"Saturday","zeg":"say (zeggen)","zeggen":"to say","zegt":"says (zeggen)",
  "zeker":"sure / certainly","zenuwachtig":"nervous","zes":"six","zestien":"sixteen","zestig":"sixty",
  "zet":"put (zetten)","zeven":"seven","zeventien":"seventeen","zeventig":"seventy","ziek":"sick",
  "ziekenhuis":"hospital (sick-house)","ziektebriefje":"sick note","ziens":"seeing","zijn":"to be / are",
  "zin":"desire / mood","zit":"sits (zitten)","zitten":"to sit","zoek":"look for (zoeken)","zondag":"Sunday",
  "zonder":"without","zorgen":"worries","zout":"salt(y)","zullen":"shall","zus":"sister","zussen":"sisters","één":"one",
};

// Word-for-word translations, only where they differ from the natural English.
const LITERAL = {
  // kassa
  "Goedendag, wat mag het zijn?":"Good day, what may it be?",
  "Wie mag ik helpen?":"Who may I help?",
  "Is het om hier op te eten of om mee te nemen?":"Is it for here up to eat or for along to take?",
  "Om mee te nemen.":"For along to take.",
  "Om hier op te eten.":"For here up to eat.",
  "Een kleine friet met mayonaise, alstublieft.":"A small fries with mayonnaise, if it pleases you.",
  "Welke saus wilt u?":"Which sauce want you?",
  "Wilt u er iets bij drinken?":"Want you there something with drink?",
  "Nog iets anders?":"Still something else?",
  "Mag ik uw naam?":"May I your name?",
  "Dat is dan twaalf euro vijftig.":"That is then twelve euro fifty.",
  "Dat is dan acht euro twintig.":"That is then eight euro twenty.",
  "Dat is dan vijftien euro.":"That is then fifteen euro.",
  "Met de kaart of cash?":"With the card or cash?",
  "U mag contactloos betalen.":"You may contactless pay.",
  "U mag uw kaart insteken.":"You may your card in-stick.",
  "Het is gelukt.":"It has succeeded.",
  "Het is niet gelukt.":"It has not succeeded.",
  "Kunt u het opnieuw proberen?":"Can you it anew try?",
  "Heeft u het gepast?":"Have you it fitting?",
  "Hier is uw wisselgeld.":"Here is your swap-money.",
  "Wilt u een ticketje?":"Want you a little ticket?",
  "Even geduld, alstublieft.":"Just patience, please.",
  "Het duurt ongeveer tien minuten.":"It lasts about ten minutes.",
  "Zit er gluten in?":"Sits there gluten in?",
  "Ik vraag het even na in de keuken.":"I ask it just after in the kitchen.",
  "Sorry, dat is op.":"Sorry, that is up (used up).",
  "Sorry, dat hebben we niet.":"Sorry, that have we not.",
  "Ik roep even mijn collega.":"I call just my colleague.",
  "Kunt u dat herhalen, alstublieft?":"Can you that repeat, please?",
  "Smakelijk!":"Tasty!",
  "Bedankt en nog een fijne dag!":"Thanked and still a nice day!",
  // kitchen
  "Goeiemorgen allemaal!":"Good morning all-together!",
  "Wat moet ik doen?":"What must I do?",
  "Wat moet ik eerst doen?":"What must I first do?",
  "Kun je dit snijden?":"Can you this cut?",
  "Snij de uien in blokjes.":"Cut the onions in little blocks.",
  "Snij het in reepjes.":"Cut it in little strips.",
  "Snij het in plakjes.":"Cut it in little slices.",
  "Zet dit in de frigo.":"Set this in the fridge.",
  "Haal het uit de diepvries.":"Fetch it out of the deep-freeze.",
  "Zet de oven op tweehonderd graden.":"Set the oven on two-hundred degrees.",
  "Waar staat de grote pan?":"Where stands the big pan?",
  "Heet! Pas op!":"Hot! Watch up!",
  "Hoeveel moet ik er maken?":"How many must I of-them make?",
  "Ik ben bijna klaar.":"I am almost ready.",
  "Ik ben klaar, wat nu?":"I am ready, what now?",
  "We hebben geen tomaten meer.":"We have no tomatoes more.",
  "Is dit gaar?":"Is this done?",
  "Het is nog niet gaar.":"It is still not done.",
  "Proef eens.":"Taste once.",
  "Er mist iets.":"There misses something.",
  "Kun je de afwas doen?":"Can you the wash-up do?",
  "Kun je de vloer dweilen?":"Can you the floor mop?",
  "Maak je werkplek proper.":"Make your work-spot clean.",
  "Kun je even helpen?":"Can you just help?",
  "Ik heb me gesneden.":"I have myself cut.",
  "Ik heb me verbrand.":"I have myself burnt.",
  "Waar is de verbandkist?":"Where is the bandage-chest?",
  "de snijplank":"the cut-plank",
  "de koekenpan":"the cake-pan",
  "de kookpot":"the cook-pot",
  "de handschoenen":"the hand-shoes",
  // shifts
  "Wanneer moet ik werken?":"When must I work?",
  "Wanneer is mijn volgende shift?":"When is my following shift?",
  "Hoe laat begin ik morgen?":"How late begin I tomorrow?",
  "Hoe laat stop ik vandaag?":"How late stop I today?",
  "Wie sluit vandaag af?":"Who closes today off?",
  "Is het uurrooster al klaar?":"Is the hour-schedule already ready?",
  "Kan ik zaterdag vrij krijgen?":"Can I Saturday free get?",
  "Kan ik met iemand wisselen?":"Can I with someone swap?",
  "Ik kan vandaag niet komen, ik ben ziek.":"I can today not come, I am sick.",
  "Ik ben tien minuten te laat, sorry.":"I am ten minutes too late, sorry.",
  "Mag ik even pauze nemen?":"May I just break take?",
  "Ik neem even pauze.":"I take just break.",
  "Ik heb een vraag over mijn loon.":"I have a question about my wage.",
  "Waar is mijn loonbrief?":"Where is my wage-letter?",
  "Hoeveel uren heb ik deze week?":"How many hours have I this week?",
  "Ik kan extra uren doen.":"I can extra hours do.",
  "Wat moet ik nog doen voor ik ga?":"What must I still do before I go?",
  "Mag ik naar huis?":"May I to home?",
  "Goed gewerkt vandaag!":"Well worked today!",
  "Bedankt voor je hulp.":"Thanked for your help.",
  "Tot morgen, allemaal!":"Until tomorrow, all-together!",
  // meeting
  "Hoe heet je?":"How are-called you?",
  "Ik heet Alex.":"I am-called Alex.",
  "Aangenaam!":"Pleasant!",
  "Hoe gaat het met je?":"How goes it with you?",
  "Goed, en met jou?":"Good, and with you?",
  "Het gaat goed, dank je.":"It goes well, thank you.",
  "Waar kom je vandaan?":"Where come you from?",
  "Ik kom uit Spanje.":"I come out of Spain.",
  "Waar woon je?":"Where live you?",
  "Hoe lang woon je al hier?":"How long live you already here?",
  "Ik woon hier al een jaar.":"I live here already a year.",
  "Wat doe je?":"What do you?",
  "Ik studeer aan de KdG.":"I study at the KdG.",
  "Ik ben twintig jaar.":"I am twenty year.",
  "Spreek je Engels?":"Speak you English?",
  "Ik leer Nederlands.":"I learn Dutch.",
  "Ik spreek een beetje Nederlands.":"I speak a little-bit Dutch.",
  "Dank je, ik doe mijn best.":"Thank you, I do my best.",
  "Leuk je te ontmoeten!":"Nice you to meet!",
  "Tot ziens!":"Until seeing!",
  "Tot later!":"Until later!",
  // small talk
  "Wat een mooi weer, hè!":"What a beautiful weather, huh!",
  "Het regent weer.":"It rains again.",
  "Wat ga je dit weekend doen?":"What go you this weekend do?",
  "Heb je een leuk weekend gehad?":"Have you a nice weekend had?",
  "Ik ga naar de stad.":"I go to the town.",
  "Ik moet werken.":"I must work.",
  "Ik hou van sporten.":"I hold of sporting.",
  "Ik hou van muziek.":"I hold of music.",
  "Ik kijk graag naar films.":"I look gladly at films.",
  "Ik kook graag.":"I cook gladly.",
  "Welke muziek vind je leuk?":"Which music find you nice?",
  "Heb je broers of zussen?":"Have you brothers or sisters?",
  "Dat klopt.":"That knocks (adds up).",
  "Ik ook!":"I also!",
  "Ik ook niet.":"I also not.",
  // understanding
  "Sorry, ik begrijp het niet.":"Sorry, I understand it not.",
  "Kun je dat herhalen?":"Can you that repeat?",
  "Kun je langzamer praten?":"Can you slower talk?",
  "Wat betekent dat?":"What means that?",
  "Wat betekent dit woord?":"What means this word?",
  "Hoe zeg je dat in het Nederlands?":"How say you that in the Dutch?",
  "Hoe spreek je dit uit?":"How speak you this out?",
  "Hoe spel je dat?":"How spell you that?",
  "Kun je dat opschrijven?":"Can you that up-write?",
  "Kun je het in het Engels zeggen?":"Can you it in the English say?",
  "Bedoel je dit?":"Mean you this?",
  "Ik weet niet hoe je dat zegt.":"I know not how you that say.",
  "Ik ben nog aan het leren.":"I am still at the learning.",
  "Verbeter me gerust.":"Correct me without worry.",
  "Een momentje, alsjeblieft.":"A little moment, please.",
  "Ah, nu begrijp ik het!":"Ah, now understand I it!",
  "Wablieft?":"What does it please (you)?",
  // opinions
  "Ik vind het leuk.":"I find it nice.",
  "Ik vind het niet leuk.":"I find it not nice.",
  "Ik vind het lekker.":"I find it tasty.",
  "Dat vind ik ook.":"That find I also.",
  "Ik denk het wel.":"I think it indeed.",
  "Ik denk het niet.":"I think it not.",
  "Ik ben het met je eens.":"I am it with you one (agreed).",
  "Ik heb het druk.":"I have it busy.",
  "Ik heb honger.":"I have hunger.",
  "Ik heb dorst.":"I have thirst.",
  "Ik heb het koud.":"I have it cold.",
  "Ik heb het warm.":"I have it warm.",
  "Dat maakt niet uit.":"That makes not out.",
  "Wat jammer!":"What pity!",
  "Proficiat!":"May it profit (you)! (from Latin)",
  "Veel succes!":"Much success!",
  "Beterschap!":"Better-ship!",
  // shop
  "Goedendag!":"Good day!",
  "Kan ik u helpen?":"Can I you help?",
  "Ik kijk gewoon even rond.":"I look just briefly around.",
  "Ik zoek een jas.":"I seek a coat.",
  "Ik zoek een cadeau.":"I seek a present.",
  "Welke maat heeft u?":"Which size have you?",
  "Heeft u dit in een andere maat?":"Have you this in an other size?",
  "Heeft u dit in een andere kleur?":"Have you this in an other colour?",
  "Mag ik dit passen?":"May I this fit?",
  "Waar zijn de paskamers?":"Where are the try-rooms?",
  "Hoeveel kost dit?":"How-much costs this?",
  "Dat is te duur.":"That is too dear.",
  "Is er korting?":"Is there discount?",
  "Ik neem het.":"I take it.",
  "Mag ik met de kaart betalen?":"May I with the card pay?",
  "Wilt u een zakje?":"Want you a little bag?",
  "Wilt u het ticketje?":"Want you the little ticket?",
  "Mag ik dit ruilen?":"May I this exchange?",
  "Mag ik dit terugbrengen?":"May I this back-bring?",
  "Nog een prettige dag!":"Still a pleasant day!",
  // supermarket
  "Waar vind ik de melk?":"Where find I the milk?",
  "Waar liggen de eieren?":"Where lie the eggs?",
  "Heeft u nog brood?":"Have you still bread?",
  "Is dit in promotie?":"Is this in promotion?",
  "Heeft u een klantenkaart?":"Have you a customers-card?",
  "Nee, die heb ik niet.":"No, that have I not.",
  "Mag ik een zakje?":"May I a little bag?",
  "een winkelkar":"a shop-cart",
  "een mandje":"a little basket",
  // bakery
  "Wie is er aan de beurt?":"Who is there at the turn?",
  "Ik ben aan de beurt.":"I am at the turn.",
  "Een wit brood, alstublieft.":"A white bread, please.",
  "Een bruin brood, alstublieft.":"A brown bread, please.",
  "Gesneden, alstublieft.":"Cut, please.",
  "Niet gesneden, alstublieft.":"Not cut, please.",
  "Vier koffiekoeken, alstublieft.":"Four coffee-cakes, please.",
  "Mag het iets meer zijn?":"May it something more be?",
  "Nee, dat is alles.":"No, that is everything.",
  "Dat is alles, dank u.":"That is everything, thank you.",
  "Tot hoe laat bent u open?":"Until how late are you open?",
  "Hoeveel kost een brood?":"How-much costs a bread?",
  "Heeft u nog pistolets?":"Have you still rolls?",
  // café
  "Heeft u een reservatie?":"Have you a reservation?",
  "Ik heb gereserveerd op naam van Peeters.":"I have reserved on name of Peeters.",
  "Mag ik de kaart, alstublieft?":"May I the card, please?",
  "Wat wilt u drinken?":"What want you drink?",
  "Ik wil graag een cola.":"I want gladly a cola.",
  "Een pintje, alstublieft.":"A little pint, please.",
  "Nog een pintje, alstublieft.":"Still a little pint, please.",
  "Een kraantjeswater, alstublieft.":"A little-tap water, please.",
  "Plat of bruis?":"Flat or fizz?",
  "Wat raadt u aan?":"What advise you on?",
  "Wat is de dagschotel?":"What is the day-dish?",
  "Ik neem de soep.":"I take the soup.",
  "Voor mij de spaghetti.":"For me the spaghetti.",
  "Ik ben allergisch voor noten.":"I am allergic for nuts.",
  "Zit er vlees in?":"Sits there meat in?",
  "Alles in orde?":"Everything in order?",
  "Eet smakelijk!":"Eat tastily!",
  "Mag ik de rekening, alstublieft?":"May I the bill, please?",
  "Samen of apart?":"Together or apart?",
  "Kan ik hier met de kaart betalen?":"Can I here with the card pay?",
  "Laat maar zitten.":"Let (it) just sit.",
  // going out
  "Heb je zin om iets te drinken?":"Have you desire for something to drink?",
  "Heb je vanavond tijd?":"Have you tonight time?",
  "Zullen we iets afspreken?":"Shall we something off-speak?",
  "Waar spreken we af?":"Where speak we off?",
  "Om hoe laat?":"At how late?",
  "Zin in!":"Desire in (it)!",
  "Spijtig, ik kan niet.":"Regrettable, I can not.",
  "Ik kom wat later.":"I come some later.",
  "Ik ben er bijna.":"I am there almost.",
  "Wat drink je?":"What drink you?",
  "Ik trakteer!":"I treat!",
  "Mag ik je nummer?":"May I your number?",
  "Stuur me een berichtje.":"Send me a little message.",
  "Het was heel gezellig!":"It was very cosy!",
  "Ik moet naar huis.":"I must to home.",
  "Tot de volgende keer!":"Until the following time!",
  // getting around
  "Excuseer, waar is het station?":"Excuse, where is the station?",
  "Hoe kom ik naar het centrum?":"How come I to the centre?",
  "Is het hier dichtbij?":"Is it here close-by?",
  "Ga rechtdoor.":"Go right-through.",
  "Sla linksaf.":"Hit left-off.",
  "Sla rechtsaf.":"Hit right-off.",
  "aan de overkant":"on the over-side",
  "Waar moet ik uitstappen?":"Where must I out-step?",
  "Enkele reis of heen en terug?":"Single journey or there and back?",
  "Hoe laat vertrekt de trein?":"How late leaves the train?",
  "Van welk spoor vertrekt de trein?":"From which track leaves the train?",
  "De trein heeft vertraging.":"The train has delay.",
  "Is deze plaats vrij?":"Is this place free?",
  "Mag ik er even door?":"May I there just through?",
  // doctor
  "Ik voel me niet goed.":"I feel me not good.",
  "Ik heb hoofdpijn.":"I have head-pain.",
  "Ik heb buikpijn.":"I have belly-pain.",
  "Ik heb keelpijn.":"I have throat-pain.",
  "Ik heb koorts.":"I have fever.",
  "Ik ben verkouden.":"I am 'colded'.",
  "Ik moet veel hoesten.":"I must much cough.",
  "Ik wil een afspraak maken bij de dokter.":"I want an appointment make at the doctor.",
  "Waar doet het pijn?":"Where does it pain?",
  "Het doet hier pijn.":"It does here pain.",
  "Sinds wanneer heeft u dit?":"Since when have you this?",
  "Ik heb een ziektebriefje nodig voor mijn werk.":"I have a little sickness-letter needed for my work.",
  "Heeft u iets tegen hoofdpijn?":"Have you something against head-pain?",
  "Heeft u een voorschrift?":"Have you a fore-script?",
  "Hoe vaak moet ik dit nemen?":"How often must I this take?",
  "Drie keer per dag.":"Three time per day.",
  // city hall
  "Ik wil me inschrijven bij de gemeente.":"I want myself in-write at the municipality.",
  "Ik heb een afspraak om tien uur.":"I have an appointment at ten hour.",
  "Neem een nummertje.":"Take a little number.",
  "Welke documenten heb ik nodig?":"Which documents have I needed?",
  "Ik heb mijn huurcontract bij me.":"I have my rent-contract with me.",
  "Uw geboortedatum, alstublieft.":"Your birth-date, please.",
  "Wat is uw rijksregisternummer?":"What is your realm-register-number?",
  "Moet ik een formulier invullen?":"Must I a form in-fill?",
  "Kunt u mij helpen met dit formulier?":"Can you me help with this form?",
  "Waar moet ik tekenen?":"Where must I sign?",
  "Wanneer is mijn kaart klaar?":"When is my card ready?",
  "Ik wil een rekening openen.":"I want an account open.",
  "Mijn kaart werkt niet.":"My card works not.",
  "Ik wil een pakje versturen.":"I want a little package send.",
  "Ik kom een pakje ophalen.":"I come a little package up-fetch.",
  // phone
  "Hallo, met wie spreek ik?":"Hello, with whom speak I?",
  "Met Alex.":"With Alex.",
  "Ik bel over mijn afspraak.":"I call about my appointment.",
  "Kan ik een afspraak maken?":"Can I an appointment make?",
  "Past dinsdag om tien uur?":"Fits Tuesday at ten hour?",
  "Dat past.":"That fits.",
  "Dat past niet, sorry.":"That fits not, sorry.",
  "Kan het iets later?":"Can it something later?",
  "Kan het vroeger?":"Can it earlier?",
  "Kan ik mijn afspraak verplaatsen?":"Can I my appointment move?",
  "Ik moet mijn afspraak annuleren.":"I must my appointment cancel.",
  "Kunt u mij terugbellen?":"Can you me back-call?",
  "Ik hoor u slecht.":"I hear you badly.",
  "Ik stuur je een berichtje.":"I send you a little message.",
  // home
  "Ik woon op kot.":"I live on (a) student-room.",
  "Ik zoek een appartement.":"I seek an apartment.",
  "Hoeveel is de huur?":"How-much is the rent?",
  "Zijn de kosten inbegrepen?":"Are the costs included?",
  "Wanneer kan ik de kamer bekijken?":"When can I the room look-at?",
  "De verwarming werkt niet.":"The heating works not.",
  "Er is geen warm water.":"There is no warm water.",
  "De wifi werkt niet.":"The wifi works not.",
  "Er is een lek.":"There is a leak.",
  "Kunt u dat komen herstellen?":"Can you that come repair?",
  "Ik ben mijn sleutel vergeten.":"I am my key forgotten.",
  "Wanneer wordt het afval opgehaald?":"When becomes the rubbish up-fetched?",
  "Wie doet de afwas?":"Who does the wash-up?",
  "Kun je wat stiller zijn?":"Can you some quieter be?",
  "de huisbaas":"the house-boss",
  "de badkamer":"the bath-room",
  "de slaapkamer":"the sleep-room",
  // school
  "Hoe laat begint de les?":"How late begins the lesson?",
  "Ik ben te laat, sorry.":"I am too late, sorry.",
  "Mag ik een vraag stellen?":"May I a question put?",
  "Waar kan ik dat vinden?":"Where can I that find?",
  "Kun je me helpen?":"Can you me help?",
  "Zullen we samenwerken?":"Shall we together-work?",
  "Wanneer heb je tijd?":"When have you time?",
  "Ik begrijp de opdracht niet.":"I understand the assignment not.",
  "Mag ik je notities lenen?":"May I your notes borrow?",
  "Ik ben klaar.":"I am ready.",
  "Ik heb pauze.":"I have break.",
  "Tot morgen!":"Until tomorrow!",
  // emergencies
  "Ik heb hulp nodig.":"I have help needed.",
  "Bel honderdtwaalf!":"Call hundred-twelve!",
  "Er is een ongeluk gebeurd.":"There is an un-luck happened.",
  "Gaat het?":"Goes it?",
  "Ik heb een dokter nodig.":"I have a doctor needed.",
  "Waar is het ziekenhuis?":"Where is the sick-house?",
  "Ik ben bestolen.":"I am robbed.",
  "Ik ben mijn portefeuille kwijt.":"I am my wallet lost.",
  "Ik ben mijn gsm kwijt.":"I am my mobile lost.",
  "Ik ben verdwaald.":"I am strayed.",
  // essentials
  "alstublieft":"if it pleases you",
  "alsjeblieft":"if it pleases you (informal)",
  "graag gedaan":"gladly done",
  "Ik weet het niet.":"I know it not.",
  "Mag ik iets vragen?":"May I something ask?",
  "misschien":"may happen",
  // numbers & time
  "vijfentwintig":"five-and-twenty",
  "Hoe laat is het?":"How late is it?",
  "Het is drie uur.":"It is three hour.",
  "om acht uur":"at eight hour",
  "half drie":"half three",
  "kwart voor vijf":"quarter before five",
  "volgende week":"following week",
};

// Split ("separable") verbs: the prefix jumps to the end of a normal sentence.
const SPLIT_VERBS = [
  [/\bvraag\b.*\bna\b/, 'vraag … na', 'navragen', 'to check / find out'],
  [/\bsluit\b.*\baf\b/, 'sluit … af', 'afsluiten', 'to lock up / close'],
  [/\bkijk\b.*\brond\b/, 'kijk … rond', 'rondkijken', 'to look around'],
  [/\bspreken we af\b/, 'spreken … af', 'afspreken', 'to arrange to meet'],
  [/\bspreek je dit uit\b/, 'spreek … uit', 'uitspreken', 'to pronounce'],
  [/\braadt u aan\b/, 'raadt … aan', 'aanraden', 'to recommend'],
  [/\bpas op\b/, 'pas op', 'oppassen', 'to watch out'],
];
const JOINED_VERBS = {
  opschrijven: 'Ik schrijf het op.', terugbellen: 'Ik bel u terug.', terugbrengen: 'Ik breng het terug.',
  uitstappen: 'Ik stap hier uit.', invullen: 'Ik vul het formulier in.', insteken: 'Ik steek mijn kaart in.',
  inschrijven: 'Ik schrijf me in.', ophalen: 'Ik haal het pakje op.', samenwerken: 'We werken samen.',
  afspreken: 'We spreken morgen af.', meenemen: 'Ik neem het mee.', opeten: 'Ik eet het op.',
};
const MODALS = /\b(moet|moeten|kan|kun|kunt|wil|wilt|mag|zullen)\b/;
const PARTICIPLES = /\b(gehad|gereserveerd|gesneden|gewerkt|gebeurd|gelukt|gedaan|bestolen|verbrand|vergeten|verdwaald)\b/;
const IMPERATIVES = /^(snij|zet|haal|ga|sla|neem|was|maak|proef|bel|stuur|schil|verbeter)\b/;

// Grammar tips: [test(dutch lowercased, english), html]. A card shows every tip that matches (max 4).
const TIPS = [
  [n => SPLIT_VERBS.some(([re]) => re.test(n)), n => {
    const [, shown, verb, mean] = SPLIT_VERBS.find(([re]) => re.test(n));
    return `<b>Split verb:</b> “${shown}” comes from <b>${verb}</b> (${mean}). In a normal sentence the verb goes second and its prefix jumps to the very end.`; }],
  [n => /\bmee te nemen\b/.test(n), () => `<b>Split verb:</b> <b>meenemen</b> (to take along). With “te” it splits in the middle: mee-te-nemen.`],
  [n => /\bop te eten\b/.test(n), () => `<b>Split verb:</b> <b>opeten</b> (to eat up). With “te” it splits in the middle: op-te-eten.`],
  [n => Object.keys(JOINED_VERBS).some(v => new RegExp(`\\b${v}\\b`).test(n)) && /\s/.test(n), n => {
    const v = Object.keys(JOINED_VERBS).find(v => new RegExp(`\\b${v}\\b`).test(n));
    return `<b>${v}</b> is a split verb. Here it stays in one piece because it's at the end, but in a normal sentence the prefix splits off: <i>${JOINED_VERBS[v]}</i>`; }],
  [n => /\bopgehaald\b/.test(n), () => `<b>worden + participle</b> = passive (“is being done”). In split verbs the <b>ge-</b> goes in the middle: op-<b>ge</b>-haald.`],
  [n => /\beven\b/.test(n), () => `<b>even</b> = “just / quickly”. A softener Flemish people put in almost every request — without it the sentence can sound blunt.`],
  [n => /\beens\b/.test(n) && !/met je eens/.test(n), () => `<b>eens</b> here is a softener, like “just”: <i>Proef eens</i> = “Have a taste”.`],
  [n => /\bmet je eens\b/.test(n), () => `<b>het eens zijn met</b> = to agree with. Fixed expression — learn it as a whole.`],
  [n => /\bgraag\b/.test(n) && !/graag gedaan/.test(n), () => `<b>graag</b> = “gladly”. <i>Ik wil graag…</i> = “I'd like…”, and verb + graag = “like doing”: <i>Ik kook graag</i> = I like cooking.`],
  [n => /alstublieft/.test(n), () => `<b>alstublieft</b> = “als het u belieft” (if it pleases you) — the polite “please”. It also means “here you are” when handing something over. Informal: <b>alsjeblieft</b>.`],
  [n => /alsjeblieft/.test(n), () => `<b>alsjeblieft</b> = informal “please / here you are”. With customers and strangers use <b>alstublieft</b>.`],
  [n => /\b(u|uw)\b/.test(n), () => `<b>u</b> = polite “you” (customers, strangers, older people), <b>uw</b> = “your”. Verbs take the -t form: <i>u heeft, u kunt, u wilt</i>.`],
  [n => /^(mag|kan|kun|kunt|heeft|heb|wilt|is|zijn|zit|past|spreek|zullen|bedoel|moet|gaat)\b.*\?$/.test(n), () => `<b>Yes/no questions start with the verb.</b> Dutch has no “do”: <i>Heeft u…?</i> = “Do you have…?”, <i>Spreek je…?</i> = “Do you speak…?”`],
  [n => /^mag ik\b/.test(n) && !/\b\w+en\?$/.test(n), () => `<b>Mag ik …?</b> (“May I …?”) is the standard way to ask for something — no verb needed: <i>Mag ik de rekening?</i> = Can I have the bill?`],
  [n => /\b(\w+[^t]) je\b.*\?$/.test(n) && /^(\w+ )?(spreek|woon|kom|doe|heb|kun|bedoel|drink|ga|heet|spel|zeg|vind)\b/.test(n), () => `<b>Verb before “je”:</b> the -t drops off. <i>Jij woont → Woon je?</i>, <i>Jij spreekt → Spreek je?</i>`],
  [n => MODALS.test(n) && /\b\w+en[.?!]*$/.test(n) && !/^(\w+ )?(moeten|zullen)[.?!]*$/.test(n), () => `<b>Second verb goes to the end.</b> With moeten / kunnen / willen / mogen / zullen, the other verb waits until the very end: <i>Ik kan vandaag niet <b>komen</b>.</i>`],
  [n => PARTICIPLES.test(n) && !/\bwordt\b/.test(n), () => `<b>Past tense (perfect):</b> hebben/zijn + past participle at the end, usually starting with <b>ge-</b>: <i>Ik heb gereserveerd</i> = I (have) reserved.`],
  [n => /\bkwijt\b/.test(n), () => `<b>kwijt zijn</b> = to have lost: <i>Ik ben mijn gsm kwijt</i> (literally “I am my phone lost”).`],
  [n => /\ber\b/.test(n), () => `<b>er</b> is a small filler word: “there” (<i>Er is een lek</i>), “of it/them” (<i>Hoeveel moet ik er maken?</i>), or pointing at something (<i>Zit er vlees in?</i>).`],
  [n => n.split(/[^a-zà-ÿ]+/).some(w => /(tje|je|pje)s?$/.test(w) && w.length > 4 && !/^(alsjeblieft|meisje)$/.test(w)), () => `<b>-je / -tje</b> = “little …” (diminutive). Flemish uses it all the time just to sound friendly: <i>een pintje, een ticketje, een momentje</i>. These words always take <b>het</b>.`],
  [n => /\bheb (honger|dorst|koorts|hoofdpijn|buikpijn|keelpijn|pauze)\b/.test(n), () => `Dutch says you <b>have</b> hunger, thirst, pain or fever: <i>Ik heb honger</i> = I'm hungry.`],
  [n => /\bheb het (koud|warm|druk)\b/.test(n), () => `<b>Ik heb het koud</b> = I'm cold. Never “Ik ben koud” — that means you're a cold person!`],
  [n => /\bniet[.?!]*$/.test(n), () => `<b>niet</b> (not) often goes at the very end: <i>Ik begrijp het niet.</i>`],
  [n => /\bgeen\b/.test(n), () => `<b>geen</b> = “no / not a / not any”. Use it before nouns instead of “niet een”: <i>geen probleem, geen tomaten</i>.`],
  [n => /(^|, )(dat|die|nu)\s+\w+\s+(ik|we|je|u)\b/.test(n), () => `<b>The verb is always 2nd.</b> If the sentence starts with something other than the subject, subject and verb swap: <i>Dat vind ik ook</i> (“That find I too”).`],
  [n => /\bhou van\b/.test(n), () => `<b>houden van</b> = to love / really like (literally “hold of”).`],
  [n => /\bvind\b/.test(n), () => `<b>vinden</b> = to find → also “to think (opinion)”. <i>Ik vind het leuk</i> = I like it (“I find it nice”).`],
  [n => /\bom\b.*\bte \w+en\b/.test(n) || /\bje te \w+en\b/.test(n), () => `<b>(om) … te + verb</b> = “(in order) to …”: <i>om iets te drinken</i> = to drink something.`],
  [n => IMPERATIVES.test(n), () => `<b>Command:</b> just the verb stem, first in the sentence: <i>Snij</i> (snijden), <i>Zet</i> (zetten). Add <i>even</i> or <i>alstublieft</i> to sound friendlier.`],
  [n => /\b(staat|liggen)\b/.test(n), () => `Dutch says where things <b>stand</b> or <b>lie</b> instead of “are”: upright things <i>staan</i> (de pan staat…), flat things <i>liggen</i> (de eieren liggen…).`],
  [n => /\bhè\b/.test(n), () => `<b>hè</b> at the end = “right?” / “isn't it?” — asking for agreement.`],
  [n => /^(de|het) [a-zà-ÿ]+$/.test(n), () => `<b>de or het?</b> Dutch has two words for “the”. There's no reliable rule — learn each noun with its article. Plurals always take <b>de</b>.`],
  [n => /\bhoe laat\b/.test(n), () => `<b>Hoe laat?</b> (literally “how late?”) = “What time?”`],
  [n => /^half \w+/.test(n), () => `<b>half drie</b> = half (way) to three = 2:30. Dutch counts the half towards the <b>next</b> hour!`],
  [n => /\w+en(twintig|dertig|veertig|vijftig|zestig|zeventig|tachtig|negentig)\b/.test(n), () => `Numbers 21–99 put the unit first: <b>vijf-en-twintig</b> = “five-and-twenty”.`],
  [n => /\b(voel me|heb me|me inschrijven)\b/.test(n), () => `<b>Reflexive verb:</b> “me” = myself. <i>zich voelen</i> (to feel), <i>zich snijden</i> (to cut oneself), <i>zich inschrijven</i> (to register).`],
  [n => /\bwilt u\b/.test(n), () => `<b>Wilt u …?</b> = “Would you like …?” — polite and standard with customers.`],
  [n => /\b(kun je|kan je)\b/.test(n), () => `<b>Kun je …? / Kan je …?</b> both mean “Can you …?” (informal). Formal: <b>Kunt u …?</b>`],
  [n => /\bzin\b/.test(n), () => `<b>zin hebben (in)</b> = to feel like / look forward to: <i>Heb je zin om…?</i> = Do you feel like…?`],
  [n => /^tot\b/.test(n), () => `<b>tot</b> = until: <i>Tot ziens / morgen / later</i> = until (we) see (each other) / tomorrow / later.`],
  [n => /\bis op\b/.test(n), () => `<b>op zijn</b> = to be used up / sold out.`],
  [n => /\bnog\b/.test(n), () => `<b>nog</b> = still / yet / another: <i>nog een pintje</i> = another beer, <i>nog niet</i> = not yet, <i>nog iets?</i> = anything else?`],
  [n => /\bal\b/.test(n), () => `<b>al</b> = already. Dutch uses present tense + <i>al</i> where English says “have been …ing”: <i>Ik woon hier al een jaar</i>.`],
  [(n, en) => /\bI'll\b/.test(en) && !/\b(zal|ga)\b/.test(n), () => `<b>Present tense for the near future:</b> Dutch says “I check / I call” where English says “I'll check / I'll call”.`],
  [n => /\b(hoe je dat zegt|voor ik ga)\b/.test(n), () => `After <i>hoe, voor, omdat, dat…</i> the verb moves to the <b>end</b> of that part: <i>…hoe je dat <b>zegt</b></i>.`],
];

function explainFor(card) {
  const n = card.nl.toLowerCase();
  const words = card.nl.split(/\s+/).map(w => {
    const k = w.toLowerCase().replace(/[^a-zà-ÿ'’]/g, '').replace(/’/g, "'");
    return k && { w: w.replace(/[.,!?]/g, ''), g: GLOSS[k] || '' };
  }).filter(Boolean);
  const tips = TIPS.filter(([t]) => t(n, card.en)).map(([, h]) => h(n, card.en)).slice(0, 4);
  return { literal: LITERAL[card.nl] || '', words, tips };
}
